import type { Config } from 'tailwindcss';
import animate from 'tailwindcss-animate';
import typography from '@tailwindcss/typography';

export default {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: '1rem',
        sm: '2rem',
      },
      screens: {
        default: '1100px',
      },
    },
    extend: {
      fontFamily: {
        serif: ['var(--font-source-serif)', 'serif'],
        poppins: ['var(--font-poppins)', 'sans-serif'],
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      typography: {
        DEFAULT: {
          css: {
            maxWidth: 'none',
            width: '100%',
            color: 'hsl(var(--foreground) / 0.8)',
            fontFamily: 'var(--font-source-serif)',
            fontSize: ['14px', '16px'],
            lineHeight: '1.6',
            '> *': {
              width: '100%',
            },
            'h1, h2, h3, h4, h5, h6': {
              color: 'hsl(var(--foreground))',
              fontFamily: 'var(--font-poppins)',
              fontWeight: '500',
              letterSpacing: '-0.02em',
              'scroll-margin-top': '6rem',
              width: '100%',
            },
            h1: {
              fontSize: ['2rem', '2.5rem'],
              lineHeight: '1.2',
              marginBottom: '1rem',
              marginTop: '1.25rem',
              borderBottom: '2px solid hsl(var(--border))',
              paddingBottom: '0.5rem',
            },
            h2: {
              fontSize: ['1.65rem', '2rem'],
              lineHeight: '1.3',
              marginTop: '1.25rem',
              marginBottom: '0.5rem',
              color: 'hsl(var(--primary))',
            },
            h3: {
              fontSize: ['1.35rem', '1.65rem'],
              lineHeight: '1.4',
              marginTop: '1rem',
              marginBottom: '0.5rem',
              color: 'hsl(var(--primary) / 0.9)',
            },
            p: {
              marginTop: '0.5rem',
              marginBottom: '0.5rem',
              lineHeight: '1.6',
              letterSpacing: '0',
              fontSize: ['0.9375rem', '1rem'],
              fontFamily: 'var(--font-source-serif)',
            },
            'ul, ol': {
              marginTop: '0.5rem',
              marginBottom: '0.5rem',
              paddingLeft: '1.25rem',
              fontFamily: 'var(--font-source-serif)',
            },
            li: {
              marginTop: '0.25rem',
              marginBottom: '0.25rem',
              paddingLeft: '0.375rem',
              lineHeight: '1.6',
              fontSize: ['0.9375rem', '1rem'],
              fontFamily: 'var(--font-source-serif)',
            },
            'ul > li': {
              position: 'relative',
              paddingLeft: '1.25rem',
              '&::before': {
                content: '""',
                width: '0.25rem',
                height: '0.25rem',
                borderRadius: '50%',
                backgroundColor: 'hsl(var(--primary))',
                position: 'absolute',
                left: '0.375rem',
                top: '0.625rem',
              },
            },
            'ol > li': {
              counterIncrement: 'list-counter',
              position: 'relative',
              paddingLeft: '1.5rem',
              '&::before': {
                content: 'counter(list-counter) "."',
                position: 'absolute',
                left: '0.25rem',
                color: 'hsl(var(--primary))',
                fontWeight: '500',
              },
            },
            blockquote: {
              fontStyle: 'italic',
              borderLeftWidth: '4px',
              borderLeftColor: 'hsl(var(--primary))',
              marginTop: '1rem',
              marginBottom: '1rem',
              paddingLeft: '1rem',
              paddingTop: '0.5rem',
              paddingBottom: '0.5rem',
              paddingRight: '0.75rem',
              color: 'hsl(var(--foreground) / 0.9)',
              backgroundColor: 'hsl(var(--muted))',
              borderRadius: '0.5rem',
              fontSize: ['1rem', '1.125rem'],
              boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
              fontFamily: 'var(--font-source-serif)',
            },
            img: {
              borderRadius: '0.75rem',
              marginTop: '1rem',
              marginBottom: '1rem',
              boxShadow: '0 4px 12px -2px rgba(0, 0, 0, 0.12)',
              border: '1px solid hsl(var(--border))',
            },
            code: {
              color: 'hsl(var(--primary))',
              backgroundColor: 'hsl(var(--muted))',
              borderRadius: '0.375rem',
              padding: '0.2em 0.4em',
              fontSize: '0.875em',
              fontWeight: '500',
              border: '1px solid hsl(var(--border))',
              fontFamily: 'var(--font-mono)',
            },
            pre: {
              backgroundColor: 'hsl(var(--muted))',
              borderRadius: '0.75rem',
              padding: '0.75rem',
              overflowX: 'auto',
              border: '1px solid hsl(var(--border))',
              boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
              marginTop: '0.75rem',
              marginBottom: '0.75rem',
              code: {
                backgroundColor: 'transparent',
                padding: '0',
                borderRadius: '0',
                border: 'none',
                color: 'inherit',
                fontSize: '0.875em',
                lineHeight: '1.6',
                fontFamily: 'var(--font-mono)',
              },
            },
            hr: {
              borderColor: 'hsl(var(--border))',
              marginTop: '1.5rem',
              marginBottom: '1.5rem',
              borderWidth: '2px',
              opacity: '0.5',
            },
            table: {
              width: '100%',
              tableLayout: 'auto',
              textAlign: 'left',
              marginTop: '1rem',
              marginBottom: '1rem',
              fontSize: ['0.875em', '0.9375em'],
              lineHeight: '1.5',
              border: '1px solid hsl(var(--border))',
              borderRadius: '0.5rem',
              overflow: 'hidden',
              fontFamily: 'var(--font-source-serif)',
            },
            thead: {
              borderBottomWidth: '2px',
              borderBottomColor: 'hsl(var(--border))',
              backgroundColor: 'hsl(var(--muted))',
              fontFamily: 'var(--font-poppins)',
            },
            'th, td': {
              padding: '0.625rem 0.875rem',
              borderBottomWidth: '1px',
              borderBottomColor: 'hsl(var(--border))',
            },
            th: {
              backgroundColor: 'hsl(var(--muted))',
              fontWeight: '500',
              color: 'hsl(var(--foreground))',
              letterSpacing: '0.02em',
              textTransform: 'uppercase',
              fontSize: '0.75em',
              fontFamily: 'var(--font-poppins)',
            },
            td: {
              fontFamily: 'var(--font-source-serif)',
            },
            a: {
              color: 'hsl(var(--primary))',
              textDecoration: 'none',
              fontWeight: '500',
              transition: 'all 0.2s ease',
              borderBottom: '1px solid transparent',
              fontFamily: 'var(--font-source-serif)',
              '&:hover': {
                color: 'hsl(var(--primary))',
                borderBottomColor: 'hsl(var(--primary))',
                textDecoration: 'none',
              },
            },
          },
        },
      },
    },
  },
  plugins: [animate, typography],
} satisfies Config;
